#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          ma-agent
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Agent for MaxGuage Air
# Description:       Agent for MaxGuage Air
### END INIT INFO

# Author: Gyeongwon Kim <sutt69@kaist.ac.kr>
#

NAME=mo-agent
DESC="Agent for MaxGuage Air"
DAEMON=/usr/bin/$NAME
PIDFILE=/run/$NAME.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

start () {
  log_daemon_msg "Starting $DESC" "$NAME"
  start-stop-daemon --pidfile "$PIDFILE" --start --quiet --background --exec "$DAEMON" -- \
    -pidfile "$PIDFILE" $XINETD_OPTS
  log_end_msg $?
  return
}

stop () {
  log_daemon_msg "Stopping $DESC" "$NAME"
  start-stop-daemon --pidfile "$PIDFILE" --stop --signal 9 --quiet --oknodo --exec "$DAEMON" -- \
    -pidfile "$PIDFILE" $XINETD_OPTS
  log_end_msg $?
  return
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/maxguageair {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
